### ISSUE TITLE
I have successfully run this code, but it did not respond to "[[self rac_signalForSelector:@selector(collectionView:didSelectItemAtIndexPath:) fromProtocol:@protocol(UICollectionViewDelegate)] subscribeNext:^(RACTuple *arguments)"method when I clicked item in collectionView,how to solve it?

### ISSUE THREAD

**Issue by maibou8888** [ashfurrow/FunctionalReactivePixels#46]
In the previous code, this method can be responded, and I do not know why in the new code it doesn't respond to this method,my environment is xcode7,iphone6plus.

**Comment by ashfurrow** [comment]
Hey there! Could you paste the full view controller code? It's probably setting the delegate at the wrong time – common problem to have!

**Comment by maibou8888** [comment]
i just download it,then run the project , and i found the problem,i don't know why

**Comment by ashfurrow** [comment]
Could be something that broke with Xcode 7. I'll check it out and get back to you.

**Comment by maibou8888** [comment]
Thank you .

**Comment by maibou8888** [comment]
The project is OK?

**Comment by calvingit** [comment]
i added one line code to reset the delegate to nil, then reset it to self again. It's OK now.
but i don't know why.

```
// Need to "reset" the cached values of respondsToSelector: of UIKit
    self.collectionView.delegate = nil;
    self.collectionView.delegate = self;
```

**Comment by ashfurrow** [comment]
@calvingit Interesting. UIKit queries the delegate/datasource when you set it to determine if it responds to different selectors (optional protocol methods). Since the RAC delegate changes the view controller's answers to `respondsToSelector:`, it must need to be reset. This is likely a change in iOS 9 or so that wasn't needed with the project before that. 

I see that you made a commit that fixes this issue on your fork – would you mind sending a pull request? I'd love to merge it into this repo!
